### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mysterywolf** [RTduino-libraries/TensorFlow-Lite-Micro#2]
- [x] 需要用Sconscript控制，作为独立的RT-Thread/RTduino软件包，不能用properties的方式简单加入，包括 example 的 Kconfig 选择。
- [x] 重新拉出来一个dev分支，当前的rtt-dev分支转为rtduino-port-research分支
- [x] 解决Arduino.h 中 min / max 宏冲突的问题
- [x] tfkernel 打印 log
- [x] https://github.com/RTduino-libraries/TensorFlow-Lite-Micro/commit/4633135f5df58869cc87fc48d3d5022b2d22c65f
- [x] readme 与 文档
